#!/usr/bin/env bash

main="src/main.c"
lex="src/lexer.c"
exe="tinyc"
flags=(-std=c11 -Wall -Wextra -Wpedantic -Wformat -g)

if [[ ! -f "$exe" || "$main" -nt "$exe" || "$lex" -nt "$exe" ]]; 
then
        echo -e "\033[32mCOMPILING...\033[0m\n"
        gcc "${flags[@]}" -o "$exe" "$main" "$lex"
fi

./"$exe" "$@"
